services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: todo
      DB_PASSWORD: todo
      DB_NAME: todo_db
    depends_on:
      - db

  frontend:
    image: node:24
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
